# Generated by Django 4.2.7 on 2023-11-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="friends",
            field=models.ManyToManyField(blank=True, to="app.users"),
        ),
    ]
