# Generated by Django 4.2.7 on 2023-11-30 08:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_users_friends"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="user",
        ),
    ]
