# Generated by Django 4.2.7 on 2023-12-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_remove_users_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="users",
            name="info",
        ),
        migrations.RemoveField(
            model_name="users",
            name="second_name",
        ),
        migrations.AddField(
            model_name="users",
            name="aboutme",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="users",
            name="name",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
