# Generated by Django 4.2.7 on 2023-12-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_remove_users_first_name_remove_users_info_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="key",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
